# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD$

PORTNAME=	request_store
PORTVERSION=	1.0.8
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Per-request global storage

LICENSE=	MIT

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
