# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD$

PORTNAME=	nprogress_rails
PORTVERSION=	0.1.1.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Implementation of nprogress by rstacruz

LICENSE=	MIT

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
