# $FreeBSD: head/www/rubygem-gitlab-grack/Makefile 332054 2013-10-30 03:01:19Z swills $

PORTNAME=	gitlab-grack
PORTVERSION=	2.0.0.pre
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby/Rack Git Smart-HTTP Server Handler

RUN_DEPENDS=	rubygem-rack>=1.4.1:${PORTSDIR}/www/rubygem-rack

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes


.include <bsd.port.mk>
