# $FreeBSD: head/www/rubygem-jquery-atwho-rails/Makefile 332055 2013-10-30 03:02:27Z swills $

PORTNAME=	jquery-atwho-rails
PORTVERSION=	0.4.11
CATEGORIES=	www rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	4

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	jQuery plugin that implement Github-like mentions

RUN_DEPENDS=	rubygem-generator_spec4>=0:${PORTSDIR}/devel/rubygem-generator_spec4 \
		rubygem-rspec>=0:${PORTSDIR}/devel/rubygem-rspec

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes


.include <bsd.port.mk>
