# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD$

PORTNAME=	stringex
PORTVERSION=	2.5.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	2

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Some useful extensions to the Ruby String class

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
