# $FreeBSD: head/www/rubygem-jquery-turbolinks/Makefile 332055 2013-10-30 03:02:27Z swills $

PORTNAME=	jquery-turbolinks
PORTVERSION=	2.0.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	4

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	jQuery plugin for drop-in fix binded events problem caused by Turbolinks

RUN_DEPENDS=	rubygem-railties4>=4.1.4:${PORTSDIR}/www/rubygem-railties4 \
		rubygem-turbolinks4>=0:${PORTSDIR}/www/rubygem-turbolinks4

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes


.include <bsd.port.mk>
