# $FreeBSD: head/www/rubygem-turbolinks/Makefile 332057 2013-10-30 03:04:19Z swills $

PORTNAME=	turbolinks
PORTVERSION=	2.2.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	4

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Turbolinks makes following links in your web application faster

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

RUN_DEPENDS=	rubygem-coffee-rails4>=0:${PORTSDIR}/devel/rubygem-coffee-rails4


.include <bsd.port.mk>
