# Created by: Rui Lopes (rgl ruilopes com)
# $FreeBSD: head/devel/rubygem-tzinfo/Makefile 348835 2014-03-23 06:22:34Z swills $

PORTNAME=	tzinfo
PORTVERSION=	1.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Daylight-savings aware timezone support for Ruby

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
