# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-minitest/Makefile 349520 2014-03-29 14:20:18Z swills $

PORTNAME=	minitest
PORTVERSION=	5.3.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Minitest provides a complete suite of testing facilities

LICENSE=	MIT

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
