# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD$

PORTNAME=	connection_pool
PORTVERSION=	2.0.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	2

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Generic connection pool for Ruby

RUN_DEPENDS=	rubygem-minitest>=5.0.0:${PORTSDIR}/devel/rubygem-minitest

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes


.include <bsd.port.mk>
