# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD$

PORTNAME=	therubyracer
PORTVERSION=	0.12.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Call and manipulate Ruby code and objects from JavaScript and vice versa

LICENSE=	MIT

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
