# $FreeBSD: head/www/rubygem-acts-as-taggable-on/Makefile 340905 2014-01-24 14:55:44Z miwi $

PORTNAME=	acts-as-taggable-on
PORTVERSION=	3.3.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	3

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Tag a single model on several contexts

RUN_DEPENDS=	rubygem-rails4>=4.1.6:${PORTSDIR}/www/rubygem-rails4

USE_RUBY=	YES
USE_RUBYGEMS=	YES
RUBYGEM_AUTOPLIST=	YES

.include <bsd.port.mk>
