# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD$

PORTNAME=	gitlab_meta
PORTVERSION=	7.0
CATEGORIES=	www rubygems

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	GitLab meta gem

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
